let data =
[
[
  "Hindi",
  "English",
  "Tamil",
  "Telugu",
  "Marathi",
  "Kannada",
  "Malayalam",
  "Punjabi",
  "Bengali",
  "Gujarati",
  "Oriya",
  "Rajasthani",
  "French",
  "Bhojpuri",
  "Japanese",
  "Khasi",
  "Ladakhi"
],
{
  "ET00107185": {
    "EventGroup": "EG00084189",
    "EventTitle": "Cypher - Shoonya Se Shikhar Tak",
    "EventCode": "ET00107185",
    "EventImageCode": "cypher-shoonya-se-shikhar-tak-et00107185-15-07-2019-01-24-44",
    "EventLanguage": "Hindi",
    "EventGenre": "Biography",
    "EventURL": "cypher-shoonya-se-shikhar-tak",
    "EventName": "Cypher - Shoonya Se Shikhar Tak",
    "ShowDate": "20 Sep, 2019",
    "DispReleaseDate": "SEPTEMBER 20, 2019",
    "MonthID": "201909",
    "TrailerURL": "https://www.youtube.com/watch?v=MPbbMS__hjQ",
    "AllowPreBook": "N",
    "IsAtmosEnabled": "N",
    "TentativeReleaseDate": "0",
    "EventIsDefault": "Y",
    "EventCensor": "",
    "EventDimension": "2D",
    "TrailerURLUploadDate": "2019-08-13 14:43:57",
    "LanguageSequence": "1",
    "IsMovieClubEnabled": "N",
    "IsPremiere": "N",
    "ratings": {
      "bmsRating": 0,
      "bmsCount": 0,
      "criticRating": 0,
      "criticCount": 0,
      "userRating": 0,
      "userCount": 0,
      "userReviewCount": 0,
      "avgRating": 0,
      "totalVotes": 0,
      "wtsCount": 189,
      "dwtsCount": 0,
      "maybe": 0,
      "totalWTSCount": 189,
      "wtsPerc": 100,
      "dwtsPerc": 0
    },
    "Region": [

    ],
    "wtsCount": 189,
    "dwtsCount": 0,
    "maybeCount": 0,
    "csCount": "189",
    "trailerUploadDate": 1565687637000,
    "totalVotes": 0,
    "avgRating": 0,
    "wtsPerc": 100,
    "trailerType": "cs"
  },
  "ET00072428": {
    "EventGroup": "EG00052289",
    "EventTitle": "The Zoya Factor",
    "EventCode": "ET00072428",
    "EventImageCode": "zoya-factor-et00072428-13-03-2018-10-31-31",
    "EventLanguage": "Hindi",
    "EventGenre": "Drama",
    "EventURL": "the-zoya-factor",
    "EventName": "The Zoya Factor",
    "ShowDate": "20 Sep, 2019",
    "DispReleaseDate": "SEPTEMBER 20, 2019",
    "MonthID": "201909",
    "TrailerURL": "https://www.youtube.com/watch?v=tz9TN7ixPW0",
    "AllowPreBook": "N",
    "IsAtmosEnabled": "N",
    "TentativeReleaseDate": "0",
    "EventIsDefault": "Y",
    "EventCensor": "U",
    "EventDimension": "2D",
    "TrailerURLUploadDate": "2019-08-29 13:55:57",
    "LanguageSequence": "1",
    "IsMovieClubEnabled": "N",
    "IsPremiere": "N",
    "ratings": {
      "bmsRating": 0,
      "bmsCount": 0,
      "criticRating": 0,
      "criticCount": 0,
      "userRating": 0,
      "userCount": 0,
      "userReviewCount": 0,
      "avgRating": 0,
      "totalVotes": 0,
      "wtsCount": 8206,
      "dwtsCount": 26,
      "maybe": 0,
      "totalWTSCount": 8232,
      "wtsPerc": 100,
      "dwtsPerc": 0
    },
    "Region": [

    ],
    "wtsCount": 8213,
    "dwtsCount": 26,
    "maybeCount": 0,
    "csCount": "8,239",
    "trailerUploadDate": 1567067157000,
    "totalVotes": 0,
    "avgRating": 0,
    "wtsPerc": 100,
    "trailerType": "cs"
  },
  "ET00075746": {
    "EventGroup": "EG00055545",
    "EventTitle": "Prassthanam",
    "EventCode": "ET00075746",
    "EventImageCode": "prasthaanam-et00075746-14-05-2018-05-32-47",
    "EventLanguage": "Hindi",
    "EventGenre": "Drama",
    "EventURL": "prassthanam",
    "EventName": "Prassthanam",
    "ShowDate": "20 Sep, 2019",
    "DispReleaseDate": "SEPTEMBER 20, 2019",
    "MonthID": "201909",
    "TrailerURL": "https://www.youtube.com/watch?v=iVyXJiXV7Rk&feature=youtu.be",
    "AllowPreBook": "N",
    "IsAtmosEnabled": "N",
    "TentativeReleaseDate": "0",
    "EventIsDefault": "Y",
    "EventCensor": "",
    "EventDimension": "2D",
    "TrailerURLUploadDate": "2019-08-29 16:10:55",
    "LanguageSequence": "1",
    "IsMovieClubEnabled": "N",
    "IsPremiere": "N",
    "ratings": {
      "bmsRating": 0,
      "bmsCount": 0,
      "criticRating": 0,
      "criticCount": 0,
      "userRating": 0,
      "userCount": 0,
      "userReviewCount": 0,
      "avgRating": 0,
      "totalVotes": 0,
      "wtsCount": 4070,
      "dwtsCount": 4,
      "maybe": 0,
      "totalWTSCount": 4074,
      "wtsPerc": 100,
      "dwtsPerc": 0
    },
    "Region": [

    ],
    "wtsCount": 4075,
    "dwtsCount": 4,
    "maybeCount": 0,
    "csCount": "4,079",
    "trailerUploadDate": 1567075255000,
    "totalVotes": 0,
    "avgRating": 0,
    "wtsPerc": 100,
    "trailerType": "cs"
  },
  "ET00096630": {
    "EventGroup": "EG00074583",
    "EventTitle": "Pal Pal Dil Ke Paas",
    "EventCode": "ET00096630",
    "EventImageCode": "pal-pal-dil-ke-paas-et00096630-14-02-2019-03-40-34",
    "EventLanguage": "Hindi",
    "EventGenre": "Drama|Romantic",
    "EventURL": "pal-pal-dil-ke-paas",
    "EventName": "Pal Pal Dil Ke Paas",
    "ShowDate": "20 Sep, 2019",
    "DispReleaseDate": "SEPTEMBER 20, 2019",
    "MonthID": "201909",
    "TrailerURL": "https://www.youtube.com/watch?v=1XW49GYRtJ0&feature=youtu.be",
    "AllowPreBook": "N",
    "IsAtmosEnabled": "N",
    "TentativeReleaseDate": "0",
    "EventIsDefault": "Y",
    "EventCensor": "",
    "EventDimension": "2D",
    "TrailerURLUploadDate": "2019-09-05 13:41:47",
    "LanguageSequence": "1",
    "IsMovieClubEnabled": "N",
    "IsPremiere": "N",
    "ratings": {
      "bmsRating": 0,
      "bmsCount": 0,
      "criticRating": 0,
      "criticCount": 0,
      "userRating": 0,
      "userCount": 0,
      "userReviewCount": 0,
      "avgRating": 0,
      "totalVotes": 0,
      "wtsCount": 2734,
      "dwtsCount": 1,
      "maybe": 0,
      "totalWTSCount": 2735,
      "wtsPerc": 100,
      "dwtsPerc": 0
    },
    "Region": [

    ],
    "wtsCount": 2748,
    "dwtsCount": 1,
    "maybeCount": 0,
    "csCount": "2,749",
    "trailerUploadDate": 1567671107000,
    "totalVotes": 0,
    "avgRating": 0,
    "wtsPerc": 100,
    "trailerType": "cs"
  },
  "ET00104179": {
    "EventGroup": "EG00081373",
    "EventTitle": "Rambo: Last Blood",
    "EventCode": "ET00104179",
    "EventImageCode": "rambo-last-blood-et00104179-03-06-2019-03-46-12",
    "EventLanguage": "English",
    "EventGenre": "Action|Thriller",
    "EventURL": "rambo-last-blood",
    "EventName": "Rambo: Last Blood",
    "ShowDate": "20 Sep, 2019",
    "DispReleaseDate": "SEPTEMBER 20, 2019",
    "MonthID": "201909",
    "TrailerURL": "https://www.youtube.com/watch?v=4vWg5yJuWfs",
    "AllowPreBook": "N",
    "IsAtmosEnabled": "N",
    "TentativeReleaseDate": "0",
    "EventIsDefault": "Y",
    "EventCensor": "",
    "EventDimension": "2D",
    "TrailerURLUploadDate": "2019-06-18 13:34:10",
    "LanguageSequence": "2",
    "IsMovieClubEnabled": "N",
    "IsPremiere": "N",
    "ratings": {
      "bmsRating": 0,
      "bmsCount": 0,
      "criticRating": 0,
      "criticCount": 0,
      "userRating": 0,
      "userCount": 0,
      "userReviewCount": 0,
      "avgRating": 0,
      "totalVotes": 0,
      "wtsCount": 6650,
      "dwtsCount": 0,
      "maybe": 0,
      "totalWTSCount": 6650,
      "wtsPerc": 100,
      "dwtsPerc": 0
    },
    "Region": [

    ],
    "wtsCount": 6591,
    "dwtsCount": 0,
    "maybeCount": 0,
    "csCount": "6,591",
    "trailerUploadDate": 1560845050000,
    "totalVotes": 0,
    "avgRating": 0,
    "wtsPerc": 100,
    "trailerType": "cs"
  },
  "ET00106063": {
    "EventGroup": "EG00083166",
    "EventTitle": "Diego Maradona",
    "EventCode": "ET00106063",
    "EventImageCode": "diego-maradona-et00106063-29-06-2019-02-30-02",
    "EventLanguage": "English",
    "EventGenre": "Drama",
    "EventURL": "diego-maradona",
    "EventName": "Diego Maradona",
    "ShowDate": "20 Sep, 2019",
    "DispReleaseDate": "SEPTEMBER 20, 2019",
    "MonthID": "201909",
    "TrailerURL": "https://youtu.be/mjfeSdHP2ZQ",
    "AllowPreBook": "N",
    "IsAtmosEnabled": "N",
    "TentativeReleaseDate": "0",
    "EventIsDefault": "Y",
    "EventCensor": "",
    "EventDimension": "2D",
    "TrailerURLUploadDate": "2019-06-29 02:07:25",
    "LanguageSequence": "2",
    "IsMovieClubEnabled": "N",
    "IsPremiere": "N",
    "ratings": {
      "bmsRating": 0,
      "bmsCount": 0,
      "criticRating": 0,
      "criticCount": 0,
      "userRating": 0,
      "userCount": 0,
      "userReviewCount": 0,
      "avgRating": 0,
      "totalVotes": 0,
      "wtsCount": 537,
      "dwtsCount": 0,
      "maybe": 0,
      "totalWTSCount": 537,
      "wtsPerc": 100,
      "dwtsPerc": 0
    },
    "Region": [

    ],
    "wtsCount": 537,
    "dwtsCount": 0,
    "maybeCount": 0,
    "csCount": "537",
    "trailerUploadDate": 1561754245000,
    "totalVotes": 0,
    "avgRating": 0,
    "wtsPerc": 100,
    "trailerType": "cs"
  },
  "ET00069912": {
    "EventGroup": "EG00049892",
    "EventTitle": "Ad Astra",
    "EventCode": "ET00069912",
    "EventImageCode": "ad-astra-et00069912-29-01-2018-10-04-01",
    "EventLanguage": "English",
    "EventGenre": "Drama",
    "EventURL": "ad-astra",
    "EventName": "Ad Astra",
    "ShowDate": "20 Sep, 2019",
    "DispReleaseDate": "SEPTEMBER 20, 2019",
    "MonthID": "201909",
    "TrailerURL": "https://www.youtube.com/watch?v=nxi6rtBtBM0&feature=youtu.be",
    "AllowPreBook": "N",
    "IsAtmosEnabled": "N",
    "TentativeReleaseDate": "0",
    "EventIsDefault": "Y",
    "EventCensor": "",
    "EventDimension": "2D",
    "TrailerURLUploadDate": "2019-07-18 19:53:39",
    "LanguageSequence": "2",
    "IsMovieClubEnabled": "N",
    "IsPremiere": "N",
    "ratings": {
      "bmsRating": 0,
      "bmsCount": 0,
      "criticRating": 0,
      "criticCount": 0,
      "userRating": 0,
      "userCount": 0,
      "userReviewCount": 0,
      "avgRating": 0,
      "totalVotes": 0,
      "wtsCount": 6782,
      "dwtsCount": 8,
      "maybe": 0,
      "totalWTSCount": 6790,
      "wtsPerc": 100,
      "dwtsPerc": 0
    },
    "Region": [

    ],
    "wtsCount": 6790,
    "dwtsCount": 8,
    "maybeCount": 0,
    "csCount": "6,798",
    "trailerUploadDate": 1563459819000,
    "totalVotes": 0,
    "avgRating": 0,
    "wtsPerc": 100,
    "trailerType": "cs"
  },
  "ET00103763": {
    "EventGroup": "EG00081052",
    "EventTitle": "The Goldfinch",
    "EventCode": "ET00103763",
    "EventImageCode": "the-goldfinch-et00103763-29-05-2019-10-23-25",
    "EventLanguage": "English",
    "EventGenre": "Drama",
    "EventURL": "the-goldfinch",
    "EventName": "The Goldfinch",
    "ShowDate": "20 Sep, 2019",
    "DispReleaseDate": "SEPTEMBER 20, 2019",
    "MonthID": "201909",
    "TrailerURL": "https://www.youtube.com/watch?v=r-uaclXaRco&feature=youtu.be",
    "AllowPreBook": "N",
    "IsAtmosEnabled": "N",
    "TentativeReleaseDate": "0",
    "EventIsDefault": "Y",
    "EventCensor": "",
    "EventDimension": "2D",
    "TrailerURLUploadDate": "2019-07-25 09:51:56",
    "LanguageSequence": "2",
    "IsMovieClubEnabled": "N",
    "IsPremiere": "N",
    "ratings": {
      "bmsRating": 0,
      "bmsCount": 0,
      "criticRating": 0,
      "criticCount": 0,
      "userRating": 0,
      "userCount": 0,
      "userReviewCount": 0,
      "avgRating": 0,
      "totalVotes": 0,
      "wtsCount": 1587,
      "dwtsCount": 0,
      "maybe": 0,
      "totalWTSCount": 1587,
      "wtsPerc": 100,
      "dwtsPerc": 0
    },
    "Region": [

    ],
    "wtsCount": 1591,
    "dwtsCount": 0,
    "maybeCount": 0,
    "csCount": "1,591",
    "trailerUploadDate": 1564028516000,
    "totalVotes": 0,
    "avgRating": 0,
    "wtsPerc": 100,
    "trailerType": "cs"
  },
  "ET00103771": {
    "EventGroup": "EG00081053",
    "EventTitle": "Oththa Seruppu Size-7",
    "EventCode": "ET00103771",
    "EventImageCode": "oththa-serupp-et00103771-29-05-2019-11-13-53",
    "EventLanguage": "Tamil",
    "EventGenre": "Drama|Thriller",
    "EventURL": "oththa-seruppu-size-7",
    "EventName": "Oththa Seruppu Size-7",
    "ShowDate": "20 Sep, 2019",
    "DispReleaseDate": "SEPTEMBER 20, 2019",
    "MonthID": "201909",
    "TrailerURL": "https://www.youtube.com/watch?v=zaLZimXP2Ak",
    "AllowPreBook": "N",
    "IsAtmosEnabled": "N",
    "TentativeReleaseDate": "0",
    "EventIsDefault": "Y",
    "EventCensor": "U",
    "EventDimension": "2D",
    "TrailerURLUploadDate": "2019-07-24 18:12:40",
    "LanguageSequence": "3",
    "IsMovieClubEnabled": "N",
    "IsPremiere": "N",
    "ratings": {
      "bmsRating": 0,
      "bmsCount": 0,
      "criticRating": 0,
      "criticCount": 0,
      "userRating": 0,
      "userCount": 0,
      "userReviewCount": 0,
      "avgRating": 0,
      "totalVotes": 0,
      "wtsCount": 943,
      "dwtsCount": 0,
      "maybe": 0,
      "totalWTSCount": 943,
      "wtsPerc": 100,
      "dwtsPerc": 0
    },
    "Region": [

    ],
    "wtsCount": 945,
    "dwtsCount": 0,
    "maybeCount": 0,
    "csCount": "945",
    "trailerUploadDate": 1563972160000,
    "totalVotes": 0,
    "avgRating": 0,
    "wtsPerc": 100,
    "trailerType": "cs"
  },
  "ET00104485": {
    "EventGroup": "EG00081717",
    "EventTitle": "Pizhai",
    "EventCode": "ET00104485",
    "EventImageCode": "pizhai-et00104485-07-06-2019-02-42-44",
    "EventLanguage": "Tamil",
    "EventGenre": "Drama",
    "EventURL": "pizhai",
    "EventName": "Pizhai",
    "ShowDate": "20 Sep, 2019",
    "DispReleaseDate": "SEPTEMBER 20, 2019",
    "MonthID": "201909",
    "TrailerURL": "https://www.youtube.com/watch?v=aNl64ajHLLQ&feature=youtu.be",
    "AllowPreBook": "N",
    "IsAtmosEnabled": "N",
    "TentativeReleaseDate": "0",
    "EventIsDefault": "Y",
    "EventCensor": "U",
    "EventDimension": "2D",
    "TrailerURLUploadDate": "2019-08-23 10:23:08",
    "LanguageSequence": "3",
    "IsMovieClubEnabled": "N",
    "IsPremiere": "N",
    "ratings": {
      "bmsRating": 0,
      "bmsCount": 0,
      "criticRating": 0,
      "criticCount": 0,
      "userRating": 0,
      "userCount": 0,
      "userReviewCount": 0,
      "avgRating": 0,
      "totalVotes": 0,
      "wtsCount": 196,
      "dwtsCount": 0,
      "maybe": 0,
      "totalWTSCount": 196,
      "wtsPerc": 100,
      "dwtsPerc": 0
    },
    "Region": [

    ],
    "wtsCount": 196,
    "dwtsCount": 0,
    "maybeCount": 0,
    "csCount": "196",
    "trailerUploadDate": 1566535988000,
    "totalVotes": 0,
    "avgRating": 0,
    "wtsPerc": 100,
    "trailerType": "cs"
  },
  "ET00110567": {
    "EventGroup": "EG00087351",
    "EventTitle": "Irandam Ulagaporin Kadaisi Gundu",
    "EventCode": "ET00110567",
    "EventImageCode": "irandam-ulagaporin-kadaisi-gundu-et00110567-28-08-2019-05-05-31",
    "EventLanguage": "Tamil",
    "EventGenre": "Drama",
    "EventURL": "irandam-ulagaporin-kadaisi-gundu",
    "EventName": "Irandam Ulagaporin Kadaisi Gundu",
    "ShowDate": "20 Sep, 2019",
    "DispReleaseDate": "SEPTEMBER 20, 2019",
    "MonthID": "201909",
    "TrailerURL": "https://www.youtube.com/watch?v=hV9_L6vKKno",
    "AllowPreBook": "N",
    "IsAtmosEnabled": "N",
    "TentativeReleaseDate": "1",
    "EventIsDefault": "Y",
    "EventCensor": "",
    "EventDimension": "2D",
    "TrailerURLUploadDate": "2019-08-29 12:13:06",
    "LanguageSequence": "3",
    "IsMovieClubEnabled": "N",
    "IsPremiere": "N",
    "ratings": {
      "bmsRating": 0,
      "bmsCount": 0,
      "criticRating": 0,
      "criticCount": 0,
      "userRating": 0,
      "userCount": 0,
      "userReviewCount": 0,
      "avgRating": 0,
      "totalVotes": 0,
      "wtsCount": 225,
      "dwtsCount": 0,
      "maybe": 0,
      "totalWTSCount": 225,
      "wtsPerc": 100,
      "dwtsPerc": 0
    },
    "Region": [

    ],
    "wtsCount": 226,
    "dwtsCount": 0,
    "maybeCount": 0,
    "csCount": "226",
    "trailerUploadDate": 1567060986000,
    "totalVotes": 0,
    "avgRating": 0,
    "wtsPerc": 100,
    "trailerType": "cs"
  },
  "ET00110847": {
    "EventGroup": "EG00087575",
    "EventTitle": "Super Duper",
    "EventCode": "ET00110847",
    "EventImageCode": "super-duper-et00110847-01-09-2019-04-08-52",
    "EventLanguage": "Tamil",
    "EventGenre": "Drama",
    "EventURL": "super-duper",
    "EventName": "Super Duper",
    "ShowDate": "20 Sep, 2019",
    "DispReleaseDate": "SEPTEMBER 20, 2019",
    "MonthID": "201909",
    "TrailerURL": "https://www.youtube.com/watch?v=wJ0iiYQuer8",
    "AllowPreBook": "N",
    "IsAtmosEnabled": "N",
    "TentativeReleaseDate": "0",
    "EventIsDefault": "Y",
    "EventCensor": "UA",
    "EventDimension": "2D",
    "TrailerURLUploadDate": "2019-09-04 12:05:42",
    "LanguageSequence": "3",
    "IsMovieClubEnabled": "N",
    "IsPremiere": "N",
    "ratings": {
      "bmsRating": 0,
      "bmsCount": 0,
      "criticRating": 0,
      "criticCount": 0,
      "userRating": 0,
      "userCount": 0,
      "userReviewCount": 0,
      "avgRating": 0,
      "totalVotes": 0,
      "wtsCount": 78,
      "dwtsCount": 2,
      "maybe": 0,
      "totalWTSCount": 80,
      "wtsPerc": 98,
      "dwtsPerc": 2
    },
    "Region": [

    ],
    "wtsCount": 79,
    "dwtsCount": 2,
    "maybeCount": 0,
    "csCount": "81",
    "trailerUploadDate": 1567578942000,
    "totalVotes": 0,
    "avgRating": 0,
    "wtsPerc": 98,
    "trailerType": "cs"
  },
  "ET00093234": {
    "EventGroup": "EG00071378",
    "EventTitle": "Kaappaan",
    "EventCode": "ET00093234",
    "EventImageCode": "kaappaan-et00093234-02-01-2019-04-17-09",
    "EventLanguage": "Tamil",
    "EventGenre": "Action|Thriller",
    "EventURL": "kaappaan",
    "EventName": "Kaappaan",
    "ShowDate": "20 Sep, 2019",
    "DispReleaseDate": "SEPTEMBER 20, 2019",
    "MonthID": "201909",
    "TrailerURL": "https://www.youtube.com/watch?v=j_eduSGN3RQ&feature=youtu.be",
    "AllowPreBook": "N",
    "IsAtmosEnabled": "N",
    "TentativeReleaseDate": "0",
    "EventIsDefault": "Y",
    "EventCensor": "",
    "EventDimension": "2D",
    "TrailerURLUploadDate": "2019-09-05 12:41:07",
    "LanguageSequence": "3",
    "IsMovieClubEnabled": "N",
    "IsPremiere": "N",
    "ratings": {
      "bmsRating": 0,
      "bmsCount": 0,
      "criticRating": 0,
      "criticCount": 0,
      "userRating": 0,
      "userCount": 0,
      "userReviewCount": 0,
      "avgRating": 0,
      "totalVotes": 0,
      "wtsCount": 14483,
      "dwtsCount": 7,
      "maybe": 0,
      "totalWTSCount": 14490,
      "wtsPerc": 100,
      "dwtsPerc": 0
    },
    "Region": [

    ],
    "wtsCount": 14509,
    "dwtsCount": 7,
    "maybeCount": 0,
    "csCount": "14,516",
    "trailerUploadDate": 1567667467000,
    "totalVotes": 0,
    "avgRating": 0,
    "wtsPerc": 100,
    "trailerType": "cs"
  },
  "ET00095618": {
    "EventGroup": "EG00073791",
    "EventTitle": "Ninnu Thalachi",
    "EventCode": "ET00095618",
    "EventImageCode": "ninnu-thalachi-et00095618-05-02-2019-11-40-07",
    "EventLanguage": "Telugu",
    "EventGenre": "Drama",
    "EventURL": "ninnu-thalachi",
    "EventName": "Ninnu Thalachi",
    "ShowDate": "20 Sep, 2019",
    "DispReleaseDate": "SEPTEMBER 20, 2019",
    "MonthID": "201909",
    "TrailerURL": "https://www.youtube.com/watch?v=9XAlqhGvvvk",
    "AllowPreBook": "N",
    "IsAtmosEnabled": "N",
    "TentativeReleaseDate": "0",
    "EventIsDefault": "Y",
    "EventCensor": "",
    "EventDimension": "2D",
    "TrailerURLUploadDate": "2019-02-06 14:57:50",
    "LanguageSequence": "4",
    "IsMovieClubEnabled": "N",
    "IsPremiere": "N",
    "ratings": {
      "bmsRating": 0,
      "bmsCount": 0,
      "criticRating": 0,
      "criticCount": 0,
      "userRating": 0,
      "userCount": 0,
      "userReviewCount": 0,
      "avgRating": 0,
      "totalVotes": 0,
      "wtsCount": 829,
      "dwtsCount": 2,
      "maybe": 0,
      "totalWTSCount": 831,
      "wtsPerc": 100,
      "dwtsPerc": 0
    },
    "Region": [

    ],
    "wtsCount": 829,
    "dwtsCount": 2,
    "maybeCount": 0,
    "csCount": "831",
    "trailerUploadDate": 1549445270000,
    "totalVotes": 0,
    "avgRating": 0,
    "wtsPerc": 100,
    "trailerType": "cs"
  },
  "ET00106908": {
    "EventGroup": "EG00083886",
    "EventTitle": "Bandobast",
    "EventCode": "ET00106908",
    "EventImageCode": "bandobast-et00106908-10-07-2019-04-48-58",
    "EventLanguage": "Telugu",
    "EventGenre": "Action|Drama|Thriller",
    "EventURL": "bandobast",
    "EventName": "Bandobast",
    "ShowDate": "20 Sep, 2019",
    "DispReleaseDate": "SEPTEMBER 20, 2019",
    "MonthID": "201909",
    "TrailerURL": "https://www.youtube.com/watch?v=o29rQnBpeRo&feature=youtu.be",
    "AllowPreBook": "N",
    "IsAtmosEnabled": "N",
    "TentativeReleaseDate": "0",
    "EventIsDefault": "Y",
    "EventCensor": "",
    "EventDimension": "2D",
    "TrailerURLUploadDate": "2019-08-05 12:11:49",
    "LanguageSequence": "4",
    "IsMovieClubEnabled": "N",
    "IsPremiere": "N",
    "ratings": {
      "bmsRating": 0,
      "bmsCount": 0,
      "criticRating": 0,
      "criticCount": 0,
      "userRating": 0,
      "userCount": 0,
      "userReviewCount": 0,
      "avgRating": 0,
      "totalVotes": 0,
      "wtsCount": 916,
      "dwtsCount": 0,
      "maybe": 0,
      "totalWTSCount": 916,
      "wtsPerc": 100,
      "dwtsPerc": 0
    },
    "Region": [

    ],
    "wtsCount": 928,
    "dwtsCount": 0,
    "maybeCount": 0,
    "csCount": "928",
    "trailerUploadDate": 1564987309000,
    "totalVotes": 0,
    "avgRating": 0,
    "wtsPerc": 100,
    "trailerType": "cs"
  }
  }];
  export default data;
